#pragma once

namespace mc
{
    enum ePARTICLE_TYPE : int
    {
        NONE                 = -1,
        BUBBLE               = 0,
        SMOKE                = 1,
        NOTE                 = 2,
        PORTAL               = 3,
        END_PORTAL           = 4,
        EXPLODE              = 5,
        FLAME                = 6,
        LAVA                 = 7,
        FOOTSTEP             = 8,
        SPLASH               = 9,
        LARGE_SMOKE          = 10,
        RED_DUST             = 11,
        SNOWBALL_POOF        = 12,
        SNOW_SHOVEL          = 13,
        SLIME                = 14,
        HEART                = 15,
        SUSPEND              = 16,
        DEPTH_SUSPEND        = 17,
        CRIT                 = 18,
        HUGE_EXPLOSION       = 19,
        LARGE_EXPLODE        = 20,
        TOWN_AURA            = 21,
        SPELL                = 22,
        WITCH_MAGIC          = 23,
        MOB_SPELL            = 24,
        MOB_SPELL_AMBIENT    = 25,
        DRIP_WATER           = 27,
        DRIP_LAVA            = 28,
        ENCHANTMENT_TABLE    = 29,
        ENDER                = 30,
        ANGRY_VILLAGER       = 31,
        HAPPY_VILLAGER       = 32,
        FIREWORKS_SPARK      = 33,
        WATER_WAKE           = 34,
        MAGIC_CRIT           = 35,
        INSTANT_SPELL        = 36,
        CLOUD                = 37,
        BARRIER              = 38,
        ICON_CRACK           = 39,
        BLOCK_DUST           = 40,
        DROPLET              = 41,
        MOB_APPEARANCE       = 43,
        DRAGON_BREATH        = 44,
        END_ROD              = 45,
        DAMAGE_INDICATOR     = 46,
        SWEEP_ATTACK         = 47,
        FALLING_DUST         = 48,
        TOTEM                = 49,
        BUBBLE_POP           = 52,
        CURRENT_DOWN         = 53,
        CONDUIT              = 54,
        BLOCK_CRACK          = 0x200000,
        CHEST_REFILL         = 0x300000,
        INSTANT_SPELL_CLIENT = 0x300001,
    };
} // namespace mc
