#pragma once

namespace mc
{
    enum eGameHostOption
    {
        eGameHostOption_Difficulty = 0,
        eGameHostOption_OnlineGame,
        eGameHostOption_InviteOnly,
        eGameHostOption_FriendsOfFriends,
        eGameHostOption_Gamertags,
        eGameHostOption_Tutorial,
        eGameHostOption_GameType,
        eGameHostOption_LevelType,
        eGameHostOption_Structures,
        eGameHostOption_BonusChest,
        eGameHostOption_HasBeenInCreative,
        eGameHostOption_PvP,
        eGameHostOption_TrustPlayers,
        eGameHostOption_TNT,
        eGameHostOption_FireSpreads,
        eGameHostOption_CheatsEnabled,
        eGameHostOption_HostCanFly,
        eGameHostOption_HostCanChangeHunger,
        eGameHostOption_HostCanBeInvisible,
        eGameHostOption_BedrockFog,
        eGameHostOption_NoHUD,
        eGameHostOption_All,
        eGameHostOption_DisableSaving,
    };

    enum EControllerActions
    {
        ACTION_MENU_A                 = 0,
        ACTION_MENU_B                 = 1,
        ACTION_MENU_X                 = 2,
        ACTION_MENU_Y                 = 3,
        ACTION_MENU_UP                = 4,
        ACTION_MENU_DOWN              = 5,
        ACTION_MENU_RIGHT             = 6,
        ACTION_MENU_LEFT              = 7,
        ACTION_MENU_PAGEUP            = 8,
        ACTION_MENU_PAGEDOWN          = 9,
        ACTION_MENU_RIGHT_SCROLL      = 10,
        ACTION_MENU_LEFT_SCROLL       = 11,
        ACTION_MENU_STICK_PRESS       = 12,
        ACTION_MENU_OTHER_STICK_PRESS = 13,
        ACTION_MENU_OTHER_STICK_UP    = 14,
        ACTION_MENU_OTHER_STICK_DOWN  = 15,
        ACTION_MENU_OTHER_STICK_LEFT  = 16,
        ACTION_MENU_OTHER_STICK_RIGHT = 17,
        ACTION_MENU_PAUSEMENU         = 18,
        ACTION_MENU_OK                = 19,
        ACTION_MENU_CANCEL            = 20,
        ACTION_MAX_MENU               = ACTION_MENU_CANCEL,

        MINECRAFT_ACTION_LEFT_SCROLL  = 0x23,
        MINECRAFT_ACTION_RIGHT_SCROLL = 0x24,
        MINECRAFT_ACTION_DROP         = 0x26,
        MINECRAFT_ACTION_SNEAK_TOGGLE = 0x27,
        MINECRAFT_ACTION_SPRINT       = 0x2E,
    };

    enum eXuiAction
    {
        eAppAction_Idle = 0,
        eAppAction_SaveGame,
        eAppAction_SaveGameCapturedThumbnail,
        eAppAction_ExitWorld,
        eAppAction_ExitWorldCapturedThumbnail,
        eAppAction_ExitWorldTrial,
        eAppAction_Respawn,
        eAppAction_WaitForRespawnComplete,
        eAppAction_PrimaryPlayerSignedOut,
        eAppAction_PrimaryPlayerSignedOutReturned,
        eAppAction_PrimaryPlayerSignedOutReturned_Menus,
        eAppAction_ExitPlayer,
        eAppAction_ExitPlayerPreLogin,
        eAppAction_TrialOver,
        eAppAction_ExitTrial,
        eAppAction_WaitForDimensionChangeComplete,
        eAppAction_SocialPost,
        eAppAction_SocialPostScreenshot,
        eAppAction_EthernetDisconnected,
        eAppAction_EthernetDisconnectedReturned,
        eAppAction_EthernetDisconnectedReturned_Menus,
        eAppAction_ExitAndJoinFromInvite,
        eAppAction_DashboardTrialJoinFromInvite,
        eAppAction_ExitAndJoinFromInviteConfirmed,
        eAppAction_JoinFromInvite,
        eAppAction_ChangeSessionType,
        eAppAction_SetDefaultOptions,
        eAppAction_LocalPlayerJoined,
        eAppAction_RemoteServerSave,
        eAppAction_WaitRemoteServerSaveComplete,
        eAppAction_FailedToJoinNoPrivileges,
        eAppAction_AutosaveSaveGame,
        eAppAction_AutosaveSaveGameCapturedThumbnail,
        eAppAction_ProfileReadError,
        eAppAction_DisplayLavaMessage,
        eAppAction_BanLevel,
        eAppAction_LevelInBanLevelList,
        eAppAction_ReloadTexturePack,
        eAppAction_TexturePackRequired,
        eAppAction_DebugText,
    };
} // namespace mc
